# Generated by Django 5.2.4 on 2025-09-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_type', models.CharField(choices=[('Retail', 'Retail'), ('Service', 'Service'), ('Tech Startup', 'Tech Startup'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=50)),
                ('company_size', models.CharField(choices=[('Freelancer / Solo', 'Freelancer / Solo'), ('Small Team (2-10)', 'Small Team (2-10)'), ('Medium (11-50)', 'Medium (11-50)'), ('Large (51+)', 'Large (51+)')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('problem', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
